language: go
go:
- 1.11.x
- master
env:
- GO111MODULE=on
git:
  depth: 1
notifications:
  email: false
install: true
before_script:
- go mod verify
script:
- mkdir bin
- GOOS=linux go build -o bin/assume-role-arn-linux cmd/assume-role-arn/main.go
- GOOS=darwin go build -o bin/assume-role-arn-osx cmd/assume-role-arn/main.go
- go test -v ./...
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $OAUTH_KEY
  file:
    - bin/assume-role-arn-linux
    - bin/assume-role-arn-osx
  on:
    repo: nordcloud/assume-role-arn
    tags: true

