language: go
go:
- 1.12.x
- master
env:
- GO111MODULE=on
git:
  depth: 1
notifications:
  email: false
install: true
before_script:
- go mod verify
script:
- go test -v ./...
- mkdir bin
- make build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $OAUTH_KEY
  file:
    - bin/assume-role-arn-linux
    - bin/assume-role-arn-osx
  on:
    repo: nordcloud/assume-role-arn
    tags: true

