language: go
go:
- 1.x
git:
  depth: 1
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure --vendor-only
notifications:
  email: false
script:
- go test -v ./...
- mkdir bin
- GOOS=linux go build -o bin/assume-role-arn-linux cmd/assume-role-arn/main.go
- GOOS=darwin go build -o bin/assume-role-arn-osx cmd/assume-role-arn/main.go
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: $OAUTH_KEY
  file:
    - bin/assume-role-arn-linux
    - bin/assume-role-arn-osx
  on:
    repo: nordcloud/assume-role-arn
    tags: true